# Generated by Django 4.1.5 on 2023-05-31 20:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            5,
                            31,
                            20,
                            35,
                            55,
                            650921,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("total", models.IntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detalle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                ("precio", models.IntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.venta"
                    ),
                ),
            ],
        ),
    ]
