# Generated by Django 4.2.1 on 2023-06-13 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_venta_estado_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='EN PREPARACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 20, 30, 43, 749575, tzinfo=datetime.timezone.utc)),
        ),
    ]
