# Generated by Django 4.2.1 on 2023-07-05 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_venta_fecha_suscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscrito',
            name='suscrito',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 16, 12, 15, 738516, tzinfo=datetime.timezone.utc)),
        ),
    ]
