# Generated by Django 4.2.1 on 2023-07-05 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_suscrito_suscrito_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscrito',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 16, 36, 49, 441433, tzinfo=datetime.timezone.utc)),
        ),
    ]
