# Generated by Django 4.2.1 on 2023-07-05 20:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_venta_fecha_usuariosuscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosuscrito',
            name='correo_suscrito',
            field=models.EmailField(default='example@something.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuariosuscrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 20, 28, 25, 91641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Suscrito',
        ),
    ]
