# Generated by Django 4.2.1 on 2023-07-06 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_usuariosuscrito_suscrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 1, 37, 20, 632073, tzinfo=datetime.timezone.utc)),
        ),
    ]
