# Generated by Django 4.2.1 on 2023-07-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='correo_suscrito',
            field=models.EmailField(default='example@something.com', max_length=254),
        ),
    ]
