# Generated by Django 4.2.1 on 2023-07-06 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_suscripcion_correo_suscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 1, 37, 20, 631038, tzinfo=datetime.timezone.utc)),
        ),
    ]
